---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
library(viridis)
theme_set(theme_minimal())
```

```{r}
data("ny_noaa")

noaa_df = 
  ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(tmax = as.numeric(tmax)/10,
         tmin = as.numeric(tmin)/10,
         year = as.factor(year),
         month = as.integer(month),
         day = as.integer(day)
         ) 

# Create a table to assign corresponding month names to the month numbers. 
month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )

# Add month names 
noaa_df = 
  left_join(noaa_df, month_df, by = "month")

noaa_df =
  noaa_df %>% 
  drop_na() %>%
  relocate("id", "month_name", "day", "year") %>%
  filter(year == 2010)
```


```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
x = list(title = "Month")

y = list(title = "Snowfall (mm)")

noaa_df %>% 
  filter(snow != 0) %>%
  mutate(text_label = str_c("Snow Depth: ", snwd, "mm")) %>%
  mutate(month_name = fct_reorder(month_name, month)) %>%
  plot_ly(
  x = ~month_name, y = ~snow, color = ~month_name, 
  colors = "viridis", type = "box", text = ~text_label) %>%
  layout(xaxis = x, yaxis = y, title = "Snowfall by Month")
```

### Chart C

```{r}

```

